In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import norm

In [2]:
from numpy.polynomial.legendre import legroots, legder, legval, Legendre


In [3]:

def get_gll(N):

    GLL_points = np.array([-1] + [0]*(N-1) + [1], np.float64)

    GLL_points[1:-1] += legroots(legder([0]*N+[1]))

    GLL_weights = 2/(N*(N+1)*legval(GLL_points, [0]*N+[1])**2)

    return GLL_points, GLL_weights


In [6]:
for i in range(1, 5):
    print(get_gll(i))

(array([-1.,  1.]), array([1., 1.]))
(array([-1.,  0.,  1.]), array([0.33333333, 1.33333333, 0.33333333]))
(array([-1.       , -0.4472136,  0.4472136,  1.       ]), array([0.16666667, 0.83333333, 0.83333333, 0.16666667]))
(array([-1.00000000e+00, -6.54653671e-01,  5.70290343e-17,  6.54653671e-01,
        1.00000000e+00]), array([0.1       , 0.54444444, 0.71111111, 0.54444444, 0.1       ]))
